# Generated by Django 5.0.1 on 2024-01-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reading_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.book'),
            preserve_default=False,
        ),
    ]
