# Generated by Django 5.0.1 on 2024-01-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_bookmark_alter_reading_options_alter_reading_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookmarks',
            field=models.ManyToManyField(to='main_app.bookmark'),
        ),
    ]
